#!/usr/bin/bash

. /bin/ironic-common.sh
. /bin/coreos-ipa-common.sh

export IRONIC_INSPECTOR_VLAN_INTERFACES=${IRONIC_INSPECTOR_VLAN_INTERFACES:-all}

IRONIC_CERT_FILE=/certs/ironic/tls.crt

# FIXME(dtantsur): the default is most certainly undesired
export IRONIC_AGENT_REGISTRY=${IRONIC_AGENT_REGISTRY:-quay.io/dtantsur}

wait_for_interface_or_ip

if [ -f "$IRONIC_CERT_FILE" ]; then
    export IRONIC_BASE_URL="https://${IRONIC_URL_HOST}"
else
    export IRONIC_BASE_URL="http://${IRONIC_URL_HOST}"
fi

render_j2_config /tmp/ironic-python-agent.ign.j2 "$IGNITION_FILE"
coreos-installer iso ignition embed -i "$IGNITION_FILE" -f "$ISO_FILE"
