#!/usr/bin/bash

export IRONIC_NETWORKING_ENABLED="${IRONIC_NETWORKING_ENABLED:-false}"
export IRONIC_NETWORKING_DRIVER_CONFIG_DIR="${IRONIC_NETWORKING_DRIVER_CONFIG_DIR:-${IRONIC_CONF_DIR}/drivers}"
export IRONIC_NETWORKING_JSON_RPC_HOST="${IRONIC_NETWORKING_JSON_RPC_HOST:-localhost}"
export IRONIC_NETWORKING_JSON_RPC_PORT="${IRONIC_NETWORKING_JSON_RPC_PORT:-8090}"
export IRONIC_NETWORKING_ENABLED_SWITCH_DRIVERS="${IRONIC_NETWORKING_ENABLED_SWITCH_DRIVERS:-generic-switch}"
# This is expected to be a secret mounted to this location so nothing else
# should be written to this directory.
export IRONIC_NETWORKING_SWITCH_CONFIGS="${IRONIC_NETWORKING_SWITCH_CONFIGS:-${IRONIC_CONF_DIR}/networking/switch-configs.conf}"
