#!/usr/bin/bash

set -euxo pipefail

# shellcheck disable=SC1091
. /bin/configure-ironic.sh

# NOTE(dtantsur): no retries here: this script is supposed to be run as a Job
# that is retried on failure.
exec ironic-dbsync --config-file /etc/ironic/ironic.conf upgrade
