#!/usr/bin/bash

set -eux

# shellcheck disable=SC1091
. /bin/ironic-common.sh
# shellcheck disable=SC1091
. /bin/tls-common.sh

DNSMASQ_EXCEPT_INTERFACE=${DNSMASQ_EXCEPT_INTERFACE:-lo}
TFTP_BOOT_DIR="/shared/tftpboot"
export DNS_PORT=${DNS_PORT:-0}

wait_for_interface_or_ip
if [[ "${DNS_IP:-}" == "provisioning" ]]; then
    if [[ "${IPV}" == "4" ]]; then
      export DNS_IP="${IRONIC_IP}"
    else
      export DNS_IP="[${IRONIC_IP}]"
    fi
fi

mkdir -p "${TFTP_BOOT_DIR}"
mkdir -p /shared/html

# Copy files to shared mount. Prefer a user-provided custom firmware dir,
# otherwise fall back to the image's built-in /tftpboot.
if [[ -r "${IPXE_CUSTOM_FIRMWARE_DIR}" ]]; then
    copy_ipxe_firmware "${IPXE_CUSTOM_FIRMWARE_DIR}" "${TFTP_BOOT_DIR}"
else
    copy_ipxe_firmware /tftpboot "${TFTP_BOOT_DIR}"
fi

# Template and write dnsmasq.conf
render_j2_config "/templates/dnsmasq.conf.j2" "${DNSMASQ_TEMP_DIR}/dnsmasq_temp.conf"

for iface in $(echo "$DNSMASQ_EXCEPT_INTERFACE" | tr ',' ' '); do
    sed -i -e "/^interface=.*/ a\except-interface=${iface}" "${DNSMASQ_TEMP_DIR}/dnsmasq_temp.conf"
done
cat "${DNSMASQ_TEMP_DIR}/dnsmasq_temp.conf" > "${DNSMASQ_CONF_DIR}/dnsmasq.conf"
rm "${DNSMASQ_TEMP_DIR}/dnsmasq_temp.conf"

exec /usr/sbin/dnsmasq -d -q -C "${DNSMASQ_CONF_DIR}/dnsmasq.conf"
