#!/usr/bin/bash

# shellcheck disable=SC1091
. /bin/configure-ironic.sh

# Ramdisk logs
mkdir -p /shared/log/ironic/deploy

# Allows skipping dbsync if it's done by an external job
if [[ "${IRONIC_SKIP_DBSYNC:-false}" != true ]]; then
    run_ironic_dbsync
fi

generate_cacert_bundle_initrd /shared/html/ipa-cacert-bundle

ipa_cert_update_enabled="$(test 0 -eq "${IRONIC_IPA_INSECURE:-0}" && test -n "${WEBSERVER_CACERT_FILE:-}" && echo "true" || echo "false")"
configure_restart_on_certificate_update "${ipa_cert_update_enabled}" ironic "${WEBSERVER_CACERT_FILE:-}"
configure_restart_on_certificate_update "${IRONIC_TLS_SETUP}" ironic "${IRONIC_CERT_FILE}"

configure_ironic_auth

if [[ "${BMC_TLS_ENABLED}" == "true" ]]; then
    # shellcheck disable=SC2034
    watchmedo shell-command \
        --patterns="*" \
        --ignore-directories \
        --command='cat "${BMC_CACERTS_PATH}"/* > "${BMC_CACERT_FILE}"' \
        "${BMC_CACERTS_PATH}" &
fi

exec /usr/bin/ironic --config-dir "${IRONIC_CONF_DIR}"
