#!/usr/bin/bash

# Set dummy provisioning IP to avoid interface detection issues (not needed to run IPE to service `/metrics`)
export PROVISIONING_IP="127.0.0.1"
# Set to true since running this script implies sensor data metrics are needed
# ironic-prometheus-exporter (IPE) needs to read from oslo_messaging_notifications.location (i.e content under /shared) where Ironic writes to
export SEND_SENSOR_DATA=true

# shellcheck disable=SC1091
. /bin/configure-ironic.sh
# shellcheck disable=SC1091
. /bin/ironic-common.sh

FLASK_RUN_HOST=${FLASK_RUN_HOST:-0.0.0.0}
FLASK_RUN_PORT=${FLASK_RUN_PORT:-9608}

export IRONIC_CONFIG="${IRONIC_CONF_DIR}/ironic.conf"

if [[ "${IRONIC_PROMETHEUS_EXPORTER_TLS_SETUP}" == "true" ]]; then
    configure_restart_on_certificate_update "${IRONIC_PROMETHEUS_EXPORTER_TLS_SETUP}" gunicorn "${IRONIC_PROMETHEUS_EXPORTER_CERT_FILE}"
    exec gunicorn -b "${FLASK_RUN_HOST}:${FLASK_RUN_PORT}" -w 4 \
        --certfile "${IRONIC_PROMETHEUS_EXPORTER_CERT_FILE}" \
        --keyfile "${IRONIC_PROMETHEUS_EXPORTER_KEY_FILE}" \
        ironic_prometheus_exporter.app.wsgi:application
else
    exec gunicorn -b "${FLASK_RUN_HOST}:${FLASK_RUN_PORT}" -w 4 \
        ironic_prometheus_exporter.app.wsgi:application
fi
