#!/usr/bin/bash

. /bin/tls-common.sh

. /bin/ironic-common.sh

wait_for_interface_or_ip

export IRONIC_PROXY_PORT=${IRONIC_PROXY_PORT:-${HTTP_PORT:-6386}}
export IRONIC_UPSTREAM_IP=${IRONIC_UPSTREAM_IP:-$IRONIC_IP}
export IRONIC_UPSTREAM_PORT=${IRONIC_UPSTREAM_PORT:-6385}
export IRONIC_UPSTREAM_PROTO=${IRONIC_UPSTREAM_PROTO:-$IRONIC_SCHEME}

if [[ "$IRONIC_UPSTREAM_IP" =~ .*:.* ]]; then
    export IRONIC_UPSTREAM_IP="[$IRONIC_UPSTREAM_IP]"
fi

sed -i 's/^Listen .*$/Listen [::]:'"$IRONIC_PROXY_PORT"'/' /etc/httpd/conf/httpd.conf
# Log to std out/err
sed -i -e 's%^ \+CustomLog.*%    CustomLog /dev/stderr combined%g' /etc/httpd/conf/httpd.conf
sed -i -e 's%^ErrorLog.*%ErrorLog /dev/stderr%g' /etc/httpd/conf/httpd.conf

render_j2_config /etc/httpd-proxy.conf.j2 /etc/httpd/conf.d/ironic-proxy.conf

exec /usr/sbin/httpd -DFOREGROUND
