#!/usr/bin/bash

export IRONIC_DEPLOYMENT="API"

. /bin/configure-ironic.sh

python3 -c 'import os; import sys; import jinja2; sys.stdout.write(jinja2.Template(sys.stdin.read()).render(env=os.environ))' < /etc/httpd-ironic-api.conf.j2 > /etc/httpd/conf.d/ironic.conf

IRONIC_HTTPD=${IRONIC_HTTPD:-"false"}

if "$IRONIC_HTTPD" == "true" ; then
    . /bin/runhttpd
fi
