name: build-images-action-pr

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  build_ironic:
    name: Build ironic container image
    if: github.repository == 'metal3-io/ironic-image'
    permissions:
      contents: read
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main # zizmor: ignore[unpinned-uses]
    with:
      image-name: 'ironic'
      pushImage: false
      generate-sbom: false
      sign-image: false
